steps_date:
  models:
    RNN:
      units: 1
      lr: 0.001
      m_batch_size: 8
    LSTM:
      units: 1
      lr: 0.001
      m_batch_size: 8
    BLSTM:
      units: 1
      lr: 0.001
      m_batch_size: 8
    GRU:
      units: 1
      lr: 0.001
      m_batch_size: 8
    ConvLSTM:
      units: 
      lr: 0.001
      m_batch_size: 8
  lag: [1, 7, 14, 21, 28]
  future: 1
# ------------------ 
steps_hour:
  models:
    RNN:
      units: 1
      lr: 0.01
      m_batch_size: 16
    LSTM:
      units: 1
      lr: 0.001
      m_batch_size: 16
    BLSTM:
      units: 1
      lr: 0.001
      m_batch_size: 16
    GRU:
      units: 1
      lr: 0.001
      m_batch_size: 16
    ConvLSTM:
      units: 
      lr: 0.001
      m_batch_size: 16
  lag: [24, 48, 72]
  future: 24
# ------------------
augmented_steps_date:
  models:
    RNN:
      units: 1
      lr: 0.01
      m_batch_size: 8
    LSTM:
      units: 1
      lr: 0.001
      m_batch_size: 8
    BLSTM:
      units: 1
      lr: 0.001
      m_batch_size: 8
    GRU:
      units: 1
      lr: 0.001
      m_batch_size: 8
    ConvLSTM:
      units: 1
      lr: 0.001
      m_batch_size: 8
  lag: [1, 7, 14, 21, 28]
  future: 1