steps_date:
  models:
    Baseline:
      future: 1
      lag: 1
    RNN:
      units: [64, 128, 1]
      n_hidden: 2
      lr: 0.004
      m_batch_size: 8
    LSTM:
      units: [1]
      n_hidden: 0
      lr: 0.008
      m_batch_size: 8
    BLSTM:
      units: [16, 128, 256]
      n_hidden: 2
      lr: 0.0055
      m_batch_size: 8
    GRU:
      units: [1]
      n_hidden: 0
      lr: 0.008
      m_batch_size: 8
  lag: [7, 14, 21]
  future: 1
# ------------------ 
steps_hour:
  models:
    Baseline:
      future: 24
      lag: 24
    RNN:
      units: [24]
      n_hidden: 0
      lr: 0.008
      m_batch_size: 16
    LSTM:
      units: [24]
      n_hidden: 0
      lr: 0.008
      m_batch_size: 16
    BLSTM:
      units: [24]
      n_hidden: 0
      lr: 0.008
      m_batch_size: 16
    GRU:
      units: [24]
      n_hidden: 0
      lr: 0.008
      m_batch_size: 16
  lag: [24, 48, 72]
  future: 24
# ------------------
augmented_steps_date:
  models:
    Baseline:
    RNN:
      units: [128]
      n_hidden: 0
      lr: 0.0012
      m_batch_size: 8
    LSTM:
      units: [1, 1, 16]
      n_hidden: 2
      lr: 0.008
      m_batch_size: 8
    BLSTM:
      units: [128]
      n_hidden: 0
      lr: 0.006
      m_batch_size: 8
    GRU:
      units: [128]
      n_hidden: 0
      lr: 0.0012
      m_batch_size: 8
  lag: [7, 14, 21]
  future: 1